In [1]:
import os 
os.listdir()

['.anaconda',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.git',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '500_Person_Gender_Height_Weight_Index.csv',
 'ab_tests.csv',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'CausalInferenceHW.ipynb',
 'compare_df.csv',
 'Contacts',
 'Cookies',
 'data.csv',
 'data.txt',
 'Desktop',
 'DID_test.csv',
 'Documents',
 'Downloads',
 'Favorites',
 'flights_2008.csv.bz2',
 'Links',
 'listings.csv',
 'Local Settings',
 'Math 1.ipynb',
 'Math 2.ipynb',
 'Math 3.ipynb',
 'Math 4.ipynb',
 'Math 5.ipynb',
 'Math 6.ipynb',
 'MediaGet2',
 'Mini project 1 (1).ipynb',
 'Mini project 1.ipynb',
 'Mini project ML.ipynb',
 'mini-project-questions.ipynb',
 'mini-project-questions1.ipynb',
 'MiniProject.ipynb',
 'Music',
 'NetHood',
 'normality_test.csv',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d9822360-b52b-11f0-bab3-a6282b875b5d}.TM.blf',
 'NTUSER.DAT{d9822360-b52b-11f0-bab3-a6282b875b5d}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d9822360-b52b-11f0-bab3-a6282b875b5d}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Numpy.ipynb',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'project.txt',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'StatsTestHW.ipynb',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Untitled10.ipynb',
 'Untitled11.ipynb',
 'Untitled12.ipynb',
 'Untitled13.ipynb',
 'Untitled14.ipynb',
 'Untitled15.ipynb',
 'Untitled16.ipynb',
 'Untitled17.ipynb',
 'Untitled18.ipynb',
 'Untitled19.ipynb',
 'Untitled2.ipynb',
 'Untitled20.ipynb',
 'Untitled21.ipynb',
 'Untitled22.ipynb',
 'Untitled23.ipynb',
 'Untitled24.ipynb',
 'Untitled25.ipynb',
 'Untitled26.ipynb',
 'Untitled27.ipynb',
 'Untitled28.ipynb',
 'Untitled29.ipynb',
 'Untitled3.ipynb',
 'Untitled30.ipynb',
 'Untitled31.ipynb',
 'Untitled32.ipynb',
 'Untitled33.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'users.txt',
 'Videos',
 'Блок 3 (1).ipynb',
 'главное меню',
 'Данные для тестового задания - Данные об аудитории.csv',
 'изображение.jpeg',
 'Мои документы',
 'Недообучение и Переобучение.ipynb',
 'Статистика - 2.ipynb',
 'Статистика.ipynb',
 'Шаблоны']

In [2]:
import pandas as pd

df = pd.read_csv("Данные для тестового задания - Данные об аудитории.csv")
df.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [3]:
mau = df["user_id"].nunique()
print("MAU:", mau)

MAU: 7639

In [4]:
dau = df.groupby("date")["user_id"].nunique()
print(dau)

date
2023-11-01    623
2023-11-02    649
2023-11-03    573
2023-11-04    343
2023-11-05    350
2023-11-06    660
2023-11-07    629
2023-11-08    600
2023-11-09    661
2023-11-10    583
2023-11-11    354
2023-11-12    377
2023-11-13    646
2023-11-14    687
2023-11-15    690
2023-11-16    639
2023-11-17    585
2023-11-18    412
2023-11-19    378
2023-11-20    711
2023-11-21    651
2023-11-22    608
2023-11-23    632
2023-11-24    595
2023-11-25    366
2023-11-26    372
2023-11-27    589
2023-11-28    610
2023-11-29    621
2023-11-30    620
Name: user_id, dtype: int64

In [5]:
avg_dau = dau.mean()
print("Средний DAU:", round(avg_dau))

Средний DAU: 560

In [7]:
df["date"] = pd.to_datetime(df["date"])

users_day1 = df[df["date"] == "2023-11-01"]["user_id"].unique()
users_day2 = df[df["date"] == "2023-11-02"]["user_id"].unique()

returned = set(users_day1) & set(users_day2)

retention = len(returned) / len(users_day1) * 100

round(retention,1)

26.6

In [8]:
total_users = df["user_id"].nunique()

users_with_views = df[df["view_adverts"] > 0]["user_id"].nunique()

conversion = users_with_views / total_users * 100

round(conversion,1)

46.3

In [9]:
total_views = df["view_adverts"].sum()

total_users = df["user_id"].nunique()

avg_views = total_views / total_users

round(avg_views,1)

np.float64(2.9)

In [10]:
total_users = 2000
promoters = 1200
detractors = 500

promoters_percent = promoters / total_users * 100
detractors_percent = detractors / total_users * 100

nps = promoters_percent - detractors_percent

print(nps)

35.0

In [12]:
import pandas as pd
from scipy import stats

df_ab = pd.read_csv("Данные для тестового задания - Данные АБ тестов.csv")

df_ab.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [13]:
df_ab["experiment_num"].unique()

array([1, 2, 3])

In [14]:
for exp in df_ab["experiment_num"].unique():
    
    data = df_ab[df_ab["experiment_num"] == exp]
    
    control = data[data["experiment_group"] == "control"]["revenue"]
    test = data[data["experiment_group"] == "test"]["revenue"]
    
    arpu_control = control.mean()
    arpu_test = test.mean()
    
    t_stat, p_value = stats.ttest_ind(control, test)
    
    print("Experiment:", exp)
    print("ARPU control:", round(arpu_control,2))
    print("ARPU test:", round(arpu_test,2))
    print("p-value:", p_value)
    print()

Experiment: 1
ARPU control: 722.46
ARPU test: 665.74
p-value: 0.688784211779017

Experiment: 2
ARPU control: 704.65
ARPU test: 332.93
p-value: 0.0009915972237576193

Experiment: 3
ARPU control: 663.21
ARPU test: 998.67
p-value: 0.06174290011218765

In [18]:
import pandas as pd

df_listers = pd.read_csv("Данные для тестового задания - Листеры.csv")

df_listers.head()

   user_id        date  cnt_adverts  age  cnt_contacts  revenue
0      100  2022-01-01            6   21           119       53
1      100  2022-01-02            2   21           200       18
2      100  2022-01-03            6   21           193       42
3      100  2022-01-04            2   21           143       38
4      100  2022-01-05            2   21           190       40

In [19]:
revenue_per_user = df_listers.groupby("user_id")["revenue"].sum()

avg_revenue = revenue_per_user.mean()

round(avg_revenue,1)

np.float64(156.5)

In [20]:
age_per_user = df_listers.groupby("user_id")["age"].first()

age_per_user.median()

28.0